// Possession — combined service worker.
//
// Two responsibilities :
// 1. COOP/COEP header injection for SharedArrayBuffer support on hosts
//    that can't set them (GitHub Pages, itch.io). Same dual-mode pattern
//    as the upstream coi-serviceworker.js (this file is loaded BOTH as
//    a regular <script> on the main thread, and as the registered worker).
// 2. Asset caching for offline play. On install we pre-cache every file
//    of the export listed in PRECACHE_ASSETS; on fetch we serve from cache
//    first and fall back to the network. Cache name is SHA-versioned, so a
//    new deploy invalidates old caches automatically (the activate handler
//    deletes everything that doesn't match the current SHA).
//
// The CI replaces the two placeholders below before copying this file
// into the export folder.

const CACHE_NAME = 'possession-cache-__SHA__';

let coepCredentialless = false;

if (typeof window === 'undefined') {
    // ─── Running as the service worker ────────────────────────────────────────

    // List of files to pre-cache, generated by CI from the contents of the
    // export folder. The literal "[]" is replaced with a JSON array.
    const PRECACHE_ASSETS = __PRECACHE_LIST__;

    self.addEventListener('install', (event) => {
        self.skipWaiting();
        event.waitUntil((async () => {
            const cache = await caches.open(CACHE_NAME);
            // Each URL is added independently — addAll() is atomic and would
            // abort the whole install if a single file 404'd, leaving the
            // game without any cache. cache.add() per URL means a stray
            // missing file just logs a warning while everything else lands.
            await Promise.all(PRECACHE_ASSETS.map(async (url) => {
                try {
                    await cache.add(url);
                } catch (e) {
                    console.warn('[sw] precache miss:', url, e);
                }
            }));
        })());
    });

    self.addEventListener('activate', (event) => {
        event.waitUntil((async () => {
            const keys = await caches.keys();
            await Promise.all(
                keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
            );
            await self.clients.claim();
        })());
    });

    self.addEventListener('message', (ev) => {
        if (!ev.data) return;
        if (ev.data.type === 'deregister') {
            self.registration.unregister()
                .then(() => self.clients.matchAll())
                .then((clients) => clients.forEach((c) => c.navigate(c.url)));
        } else if (ev.data.type === 'coepCredentialless') {
            coepCredentialless = ev.data.value;
        }
    });

    function withCoiHeaders(response, coepCred) {
        if (!response || response.status === 0) return response;
        const h = new Headers(response.headers);
        h.set('Cross-Origin-Embedder-Policy', coepCred ? 'credentialless' : 'require-corp');
        if (!coepCred) {
            h.set('Cross-Origin-Resource-Policy', 'cross-origin');
        }
        h.set('Cross-Origin-Opener-Policy', 'same-origin');
        return new Response(response.body, {
            status: response.status,
            statusText: response.statusText,
            headers: h,
        });
    }

    self.addEventListener('fetch', (event) => {
        const r = event.request;
        if (r.cache === 'only-if-cached' && r.mode !== 'same-origin') return;

        const request = (coepCredentialless && r.mode === 'no-cors')
            ? new Request(r, { credentials: 'omit' })
            : r;

        event.respondWith((async () => {
            // Cache-first for same-origin GET requests so the game keeps
            // working with no network once it's been loaded.
            const isSameOrigin = (() => {
                try { return new URL(r.url).origin === self.location.origin; }
                catch (_) { return false; }
            })();
            if (r.method === 'GET' && isSameOrigin) {
                const cached = await caches.match(r);
                if (cached) return withCoiHeaders(cached, coepCredentialless);
            }
            try {
                const response = await fetch(request);
                // Opportunistically refresh the cache for same-origin GETs that
                // weren't precached (e.g. assets pulled lazily by the engine).
                if (r.method === 'GET' && response && response.ok
                        && response.type === 'basic' && isSameOrigin) {
                    const clone = response.clone();
                    caches.open(CACHE_NAME).then((c) => c.put(r, clone));
                }
                return withCoiHeaders(response, coepCredentialless);
            } catch (e) {
                // Offline & not cached. For navigations, fall back to index.html
                // so the user gets the app shell instead of a network error.
                if (r.mode === 'navigate') {
                    const fallback = await caches.match('./index.html');
                    if (fallback) return withCoiHeaders(fallback, coepCredentialless);
                }
                console.warn('[sw] fetch failed:', e, r.url);
                return new Response('', { status: 504, statusText: 'Offline' });
            }
        })());
    });

} else {
    // ─── Running as a regular <script> on the main thread ────────────────────
    // Identical control flow to coi-serviceworker (register + reload once) so
    // the COOP/COEP isolation kicks in on the very first load.
    (() => {
        const reloadedBySelf = window.sessionStorage.getItem('coiReloadedBySelf');
        window.sessionStorage.removeItem('coiReloadedBySelf');
        const coepDegrading = (reloadedBySelf === 'coepdegrade');

        const coi = {
            shouldRegister: () => !reloadedBySelf,
            shouldDeregister: () => false,
            coepCredentialless: () => true,
            coepDegrade: () => true,
            doReload: () => window.location.reload(),
            quiet: false,
            ...window.coi,
        };

        const n = navigator;
        const controlling = n.serviceWorker && n.serviceWorker.controller;

        if (controlling && !window.crossOriginIsolated) {
            window.sessionStorage.setItem('coiCoepHasFailed', 'true');
        }
        const coepHasFailed = window.sessionStorage.getItem('coiCoepHasFailed');

        if (controlling) {
            const reloadToDegrade = coi.coepDegrade() && !(coepDegrading || window.crossOriginIsolated);
            n.serviceWorker.controller.postMessage({
                type: 'coepCredentialless',
                value: (reloadToDegrade || (coepHasFailed && coi.coepDegrade()))
                    ? false : coi.coepCredentialless(),
            });
            if (reloadToDegrade) {
                window.sessionStorage.setItem('coiReloadedBySelf', 'coepdegrade');
                coi.doReload('coepdegrade');
            }
            if (coi.shouldDeregister()) {
                n.serviceWorker.controller.postMessage({ type: 'deregister' });
            }
        }

        if (window.crossOriginIsolated !== false || !coi.shouldRegister()) return;
        if (!window.isSecureContext) {
            !coi.quiet && console.log('Possession SW not registered — secure context required.');
            return;
        }
        if (!n.serviceWorker) {
            !coi.quiet && console.error('Possession SW not registered — private browsing?');
            return;
        }

        n.serviceWorker.register(window.document.currentScript.src).then(
            (registration) => {
                !coi.quiet && console.log('Possession SW registered:', registration.scope);
                registration.addEventListener('updatefound', () => {
                    window.sessionStorage.setItem('coiReloadedBySelf', 'updatefound');
                    coi.doReload();
                });
                if (registration.active && !n.serviceWorker.controller) {
                    window.sessionStorage.setItem('coiReloadedBySelf', 'notcontrolling');
                    coi.doReload();
                }
            },
            (err) => console.error('Possession SW failed to register:', err)
        );
    })();
}
